#!/usr/bin/env python3
"""Extract git commit history from a repo into data.js for git-city."""
import subprocess, json, os, sys

repo = sys.argv[1] if len(sys.argv) > 1 else "/Users/zop.dev/Downloads/klydo redesign"
out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), "data.js")

basename = os.path.basename(os.path.abspath(repo))

# Get log with numstat
log = subprocess.check_output(
    ["git", "-C", repo, "log", "--all",
     "--pretty=format:%H|%an|%at|%s", "--numstat"],
    text=True
)

commits = []
current = None
for line in log.splitlines():
    if not line.strip():
        continue
    parts = line.split("|", 3)
    if len(parts) == 4 and len(parts[0]) == 40 and all(c in "0123456789abcdef" for c in parts[0]):
        if current:
            commits.append(current)
        current = {
            "hash": parts[0][:7],
            "author": parts[1],
            "ts": int(parts[2]),
            "subject": parts[3],
            "files": []
        }
        continue
    if current and "\t" in line:
        bits = line.split("\t")
        if len(bits) == 3:
            ins  = int(bits[0]) if bits[0].isdigit() else 0
            dels = int(bits[1]) if bits[1].isdigit() else 0
            path = bits[2]
            # Strip rename arrows
            if "=>" in path and "{" in path:
                # e.g. {a => b}/file.txt — keep target side
                import re
                path = re.sub(r"\{[^{}]*=> ([^{}]*)\}", r"\1", path)
            current["files"].append({"path": path, "ins": ins, "dels": dels})

if current:
    commits.append(current)

# Oldest first for chronological X positioning
commits.sort(key=lambda c: c["ts"])

payload = {"repo": basename, "commits": commits}
with open(out_path, "w") as f:
    f.write("// auto-generated by build.py — do not edit\n")
    f.write("window.COMMIT_DATA = ")
    json.dump(payload, f, indent=1)
    f.write(";\n")

total_files = sum(len(c["files"]) for c in commits)
print(f"Wrote {out_path}")
print(f"  repo: {basename}")
print(f"  commits: {len(commits)}")
print(f"  total file-changes (buildings): {total_files}")
