// auto-generated by build.py — do not edit
window.COMMIT_DATA = {
 "repo": "klydo redesign",
 "commits": [
  {
   "hash": "951f7ed",
   "author": "Ravindra Sisodia",
   "ts": 1779816884,
   "subject": "Klydo: a speculative rebrand.",
   "files": [
    {
     "path": ".gitignore",
     "ins": 46,
     "dels": 0
    },
    {
     "path": "DESIGN.md",
     "ins": 114,
     "dels": 0
    },
    {
     "path": "PRODUCT.md",
     "ins": 64,
     "dels": 0
    },
    {
     "path": "README.md",
     "ins": 32,
     "dels": 0
    },
    {
     "path": "docs/01-AUDIT.md",
     "ins": 92,
     "dels": 0
    },
    {
     "path": "docs/02-PRINCIPLES.md",
     "ins": 82,
     "dels": 0
    },
    {
     "path": "docs/03-INFORMATION-ARCHITECTURE.md",
     "ins": 161,
     "dels": 0
    },
    {
     "path": "docs/04-BRAND-SYSTEM.md",
     "ins": 274,
     "dels": 0
    },
    {
     "path": "docs/05-ROADMAP.md",
     "ins": 145,
     "dels": 0
    },
    {
     "path": "pitch/DEPLOY.md",
     "ins": 112,
     "dels": 0
    },
    {
     "path": "pitch/README.md",
     "ins": 53,
     "dels": 0
    },
    {
     "path": "pitch/build-deck.py",
     "ins": 837,
     "dels": 0
    },
    {
     "path": "pitch/email-to-ceo.md",
     "ins": 54,
     "dels": 0
    },
    {
     "path": "pitch/klydo-rebrand.pdf",
     "ins": 853,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/01-landing-hero.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/02-landing-todays-drop.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/03-landing-worn-bengaluru.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/04-landing-how-it-works.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/10-app-home.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/11-app-feed.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/12-app-drops.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/13-app-product-detail.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/14-app-bag.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/15-app-try-on.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/16-app-checkout.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/17-app-order-tracking.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/18-app-onboarding.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/19-app-brand-profile.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/20-app-notifications.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/21-app-search.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/22-app-stylist.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/23-app-you.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/24-app-saved.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/screenshots/25-app-bag-empty.png",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "web/.gitignore",
     "ins": 41,
     "dels": 0
    },
    {
     "path": "web/AGENTS.md",
     "ins": 5,
     "dels": 0
    },
    {
     "path": "web/CLAUDE.md",
     "ins": 1,
     "dels": 0
    },
    {
     "path": "web/README.md",
     "ins": 36,
     "dels": 0
    },
    {
     "path": "web/capture.mjs",
     "ins": 64,
     "dels": 0
    },
    {
     "path": "web/eslint.config.mjs",
     "ins": 18,
     "dels": 0
    },
    {
     "path": "web/next.config.ts",
     "ins": 18,
     "dels": 0
    },
    {
     "path": "web/package-lock.json",
     "ins": 6890,
     "dels": 0
    },
    {
     "path": "web/package.json",
     "ins": 30,
     "dels": 0
    },
    {
     "path": "web/postcss.config.mjs",
     "ins": 7,
     "dels": 0
    },
    {
     "path": "web/public/file.svg",
     "ins": 1,
     "dels": 0
    },
    {
     "path": "web/public/globe.svg",
     "ins": 1,
     "dels": 0
    },
    {
     "path": "web/public/next.svg",
     "ins": 1,
     "dels": 0
    },
    {
     "path": "web/public/vercel.svg",
     "ins": 1,
     "dels": 0
    },
    {
     "path": "web/public/window.svg",
     "ins": 1,
     "dels": 0
    },
    {
     "path": "web/src/app/app/b/[brand]/page.tsx",
     "ins": 305,
     "dels": 0
    },
    {
     "path": "web/src/app/app/bag/page.tsx",
     "ins": 195,
     "dels": 0
    },
    {
     "path": "web/src/app/app/checkout/page.tsx",
     "ins": 276,
     "dels": 0
    },
    {
     "path": "web/src/app/app/drops/page.tsx",
     "ins": 123,
     "dels": 0
    },
    {
     "path": "web/src/app/app/feed/page.tsx",
     "ins": 156,
     "dels": 0
    },
    {
     "path": "web/src/app/app/layout.tsx",
     "ins": 10,
     "dels": 0
    },
    {
     "path": "web/src/app/app/notifications/page.tsx",
     "ins": 266,
     "dels": 0
    },
    {
     "path": "web/src/app/app/orders/[id]/page.tsx",
     "ins": 249,
     "dels": 0
    },
    {
     "path": "web/src/app/app/orders/page.tsx",
     "ins": 181,
     "dels": 0
    },
    {
     "path": "web/src/app/app/p/[slug]/page.tsx",
     "ins": 184,
     "dels": 0
    },
    {
     "path": "web/src/app/app/page.tsx",
     "ins": 458,
     "dels": 0
    },
    {
     "path": "web/src/app/app/saved/page.tsx",
     "ins": 248,
     "dels": 0
    },
    {
     "path": "web/src/app/app/search/page.tsx",
     "ins": 220,
     "dels": 0
    },
    {
     "path": "web/src/app/app/stylist/page.tsx",
     "ins": 133,
     "dels": 0
    },
    {
     "path": "web/src/app/app/try/page.tsx",
     "ins": 218,
     "dels": 0
    },
    {
     "path": "web/src/app/app/welcome/page.tsx",
     "ins": 362,
     "dels": 0
    },
    {
     "path": "web/src/app/app/you/page.tsx",
     "ins": 181,
     "dels": 0
    },
    {
     "path": "web/src/app/favicon.ico",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "web/src/app/globals.css",
     "ins": 190,
     "dels": 0
    },
    {
     "path": "web/src/app/layout.tsx",
     "ins": 49,
     "dels": 0
    },
    {
     "path": "web/src/app/page.tsx",
     "ins": 23,
     "dels": 0
    },
    {
     "path": "web/src/components/Brands.tsx",
     "ins": 81,
     "dels": 0
    },
    {
     "path": "web/src/components/Footer.tsx",
     "ins": 118,
     "dels": 0
    },
    {
     "path": "web/src/components/Hero.tsx",
     "ins": 168,
     "dels": 0
    },
    {
     "path": "web/src/components/HowItWorks.tsx",
     "ins": 116,
     "dels": 0
    },
    {
     "path": "web/src/components/LiveTimer.tsx",
     "ins": 56,
     "dels": 0
    },
    {
     "path": "web/src/components/Mark.tsx",
     "ins": 44,
     "dels": 0
    },
    {
     "path": "web/src/components/Marquee.tsx",
     "ins": 47,
     "dels": 0
    },
    {
     "path": "web/src/components/Nav.tsx",
     "ins": 68,
     "dels": 0
    },
    {
     "path": "web/src/components/Stamp.tsx",
     "ins": 70,
     "dels": 0
    },
    {
     "path": "web/src/components/TodaysDrop.tsx",
     "ins": 182,
     "dels": 0
    },
    {
     "path": "web/src/components/WornInBengaluru.tsx",
     "ins": 93,
     "dels": 0
    },
    {
     "path": "web/src/components/app/ConfirmToast.tsx",
     "ins": 53,
     "dels": 0
    },
    {
     "path": "web/src/components/app/DropsGrid.tsx",
     "ins": 183,
     "dels": 0
    },
    {
     "path": "web/src/components/app/EmptyState.tsx",
     "ins": 85,
     "dels": 0
    },
    {
     "path": "web/src/components/app/PhoneFrame.tsx",
     "ins": 61,
     "dels": 0
    },
    {
     "path": "web/src/components/app/ProductGallery.tsx",
     "ins": 97,
     "dels": 0
    },
    {
     "path": "web/src/components/app/StatusBar.tsx",
     "ins": 49,
     "dels": 0
    },
    {
     "path": "web/src/components/app/TabBar.tsx",
     "ins": 114,
     "dels": 0
    },
    {
     "path": "web/src/components/app/icons.tsx",
     "ins": 113,
     "dels": 0
    },
    {
     "path": "web/src/components/app/products.ts",
     "ins": 175,
     "dels": 0
    },
    {
     "path": "web/src/lib/cn.ts",
     "ins": 6,
     "dels": 0
    },
    {
     "path": "web/tsconfig.json",
     "ins": 34,
     "dels": 0
    }
   ]
  },
  {
   "hash": "d6cb9ee",
   "author": "Ravindra Sisodia",
   "ts": 1779817667,
   "subject": "Flatten: move Next.js app to repo root for Vercel auto-detect",
   "files": [
    {
     "path": "DESIGN.md",
     "ins": 3,
     "dels": 3
    },
    {
     "path": "web/capture.mjs => capture.mjs",
     "ins": 1,
     "dels": 1
    },
    {
     "path": "docs/04-BRAND-SYSTEM.md",
     "ins": 1,
     "dels": 1
    },
    {
     "path": "docs/05-ROADMAP.md",
     "ins": 2,
     "dels": 2
    },
    {
     "path": "web/eslint.config.mjs => eslint.config.mjs",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "web/next.config.ts => next.config.ts",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "web/package-lock.json => package-lock.json",
     "ins": 4,
     "dels": 1
    },
    {
     "path": "web/package.json => package.json",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "pitch/DEPLOY.md",
     "ins": 11,
     "dels": 25
    },
    {
     "path": "pitch/README.md",
     "ins": 4,
     "dels": 4
    },
    {
     "path": "web/postcss.config.mjs => postcss.config.mjs",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "public/file.svg",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "public/globe.svg",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "public/next.svg",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "public/vercel.svg",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "public/window.svg",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/b/[brand]/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/bag/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/checkout/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/drops/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/feed/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/layout.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/notifications/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/orders/[id]/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/orders/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/p/[slug]/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/saved/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/search/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/stylist/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/try/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/welcome/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/app/you/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/favicon.ico",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/globals.css",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/layout.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/app/page.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/Brands.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/Footer.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/Hero.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/HowItWorks.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/LiveTimer.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/Mark.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/Marquee.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/Nav.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/Stamp.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/TodaysDrop.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/WornInBengaluru.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/app/ConfirmToast.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/app/DropsGrid.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/app/EmptyState.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/app/PhoneFrame.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/app/ProductGallery.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/app/StatusBar.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/app/TabBar.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/app/icons.tsx",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/components/app/products.ts",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "src/lib/cn.ts",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "web/tsconfig.json => tsconfig.json",
     "ins": 0,
     "dels": 0
    },
    {
     "path": "web/.gitignore",
     "ins": 0,
     "dels": 41
    },
    {
     "path": "web/AGENTS.md",
     "ins": 0,
     "dels": 5
    },
    {
     "path": "web/CLAUDE.md",
     "ins": 0,
     "dels": 1
    },
    {
     "path": "web/README.md",
     "ins": 0,
     "dels": 36
    }
   ]
  },
  {
   "hash": "19e884c",
   "author": "Ravindra Sisodia",
   "ts": 1779817727,
   "subject": "Rename package: web \u2192 klydo-rebrand",
   "files": [
    {
     "path": "package.json",
     "ins": 2,
     "dels": 2
    }
   ]
  },
  {
   "hash": "7fed252",
   "author": "Ravindra Sisodia",
   "ts": 1779881817,
   "subject": "Switch to GitHub Pages static export",
   "files": [
    {
     "path": ".github/workflows/deploy.yml",
     "ins": 55,
     "dels": 0
    },
    {
     "path": "next.config.ts",
     "ins": 12,
     "dels": 8
    },
    {
     "path": "src/app/app/bag/page.tsx",
     "ins": 1,
     "dels": 26
    },
    {
     "path": "src/app/app/orders/[id]/OrderDetailClient.tsx",
     "ins": 248,
     "dels": 0
    },
    {
     "path": "src/app/app/orders/[id]/page.tsx",
     "ins": 13,
     "dels": 246
    },
    {
     "path": "src/app/app/orders/page.tsx",
     "ins": 1,
     "dels": 34
    },
    {
     "path": "src/app/app/saved/page.tsx",
     "ins": 1,
     "dels": 34
    }
   ]
  },
  {
   "hash": "8f7efbe",
   "author": "Ravindra Sisodia",
   "ts": 1779881976,
   "subject": "Enable Pages auto-provision via configure-pages enablement flag",
   "files": [
    {
     "path": ".github/workflows/deploy.yml",
     "ins": 2,
     "dels": 0
    }
   ]
  },
  {
   "hash": "4dbbd68",
   "author": "Ravindra Sisodia",
   "ts": 1779882743,
   "subject": "Re-trigger Pages deploy",
   "files": []
  },
  {
   "hash": "ddd73ae",
   "author": "Ravindra Sisodia",
   "ts": 1779939193,
   "subject": "Make basePath env-driven so Vercel and GitHub Pages both work",
   "files": [
    {
     "path": ".github/workflows/deploy.yml",
     "ins": 1,
     "dels": 1
    },
    {
     "path": "next.config.ts",
     "ins": 11,
     "dels": 9
    }
   ]
  }
 ]
};
